# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# Allow inline HTML
MD033: false

# Allow bare URLs
MD034: false

# First line in file should be a top level heading
MD041: false

# Allow emphasis used instead of a heading
MD036: false

# Allow trailing punctuation in heading
MD026: false

# Allow multiple consecutive blank lines
MD012: false

# Allow hard tabs
MD010: false

# Allow dollar signs used before commands without showing output
MD014: false
